### ISSUE TITLE
'users' module not found

### ISSUE THREAD

**Issue by tyn-** [DeltaF1/Lua-MUD#11]
$ lua main.lua 
/
use telnet localhost 5555 to connect!
lua: main.lua:35: module 'users' not found:

**Comment by DeltaF1** [comment]
The users file is deprecated by the sql testing branch, which will be merged into master soon. Until then, create a new file 'users.lua' with the text `return {}`, and that should resolve the issue.

**Comment by DeltaF1** [comment]
Closed by db revamp. The users file is now created if missing.
