### ISSUE TITLE
Which versions of Lua are supported?

### ISSUE THREAD

**Issue by rabidt** [DeltaF1/Lua-MUD#2]
Which versions of Lua are supported?
5.1, 5.2, 5.3?

**Comment by DeltaF1** [comment]
I've been running it on 5.1, I haven't looked at other versions yet. Most of my Lua experience is from [LOVE](http://www.love2d.org), a game enigne that uses LuaJit 5.1 (afaik), so I haven't looked into newer versions of lua yet.

**Comment by DeltaF1** [comment]
Currently only supports Lua 5.1, see [Lua 5.2 branch](/Deltaf1/Lua-MUD/tree/lua5.2) for some headway on updating for later versions, as well as using more secure password hashing.
