### ISSUE TITLE
Which OS/platforms are supported?

### ISSUE THREAD

**Issue by rabidt** [DeltaF1/Lua-MUD#3]
Can't get it to run on linux (Centos6):

lua main.lua
use telnet localhost 5555 to connect!
dir: cannot access worldrooms: No such file or directory
dir: cannot access /b: No such file or directory
dir: cannot access /a-d: No such file or directory
dir: cannot access /b: No such file or directory
dir: cannot access /a-d: No such file or directory
lua: main.lua:40: attempt to index local 'f' (a nil value)
stack traceback:
        main.lua:40: in function 'loadHelpFiles'
        main.lua:48: in main chunk
        [C]: ?

**Comment by DeltaF1** [comment]
Ouch :open_mouth: 
I wrote the file-loading things with windows-specific commands, because lua doesn't have an existing file-iterating function. I'll rewrite those to check what os the server is on.

**Comment by DeltaF1** [comment]
Alright, just made a commit that _should_ fix it, I don't have a linux box available to test though.

**Comment by DeltaF1** [comment]
@Odoth Can you let me know when you can confirm that it runs on linux with the latest commit?

**Comment by rabidt** [comment]
No dice:
lua main.lua
/
use telnet localhost 5555 to connect!
ls: cannot access -: No such file or directory
ls: cannot access p: No such file or directory
lua: ./utils.lua:33: bad argument #1 to 'gmatch' (string expected, got userdata)
stack traceback:
        [C]: in function 'gmatch'
        ./utils.lua:33: in function <./utils.lua:28>
        (tail call): ?
        ./world_load.lua:15: in function 'load_rooms'
        main.lua:30: in main chunk
        [C]: ?

I'm willing to let you connect to my server to mess around, but not sure how to send the info privately.

**Comment by DeltaF1** [comment]
@Odoth Can you PM me on the TMC forums? Either that or email me, delyaerricson@gmail.com

**Comment by DeltaF1** [comment]
@Odoth Can you confirm that it's working for you on your machine?

**Comment by rabidt** [comment]
Yes it's working now.
